'use client';

import { useState } from 'react';
import { Download, FileText, Printer, Copy, X, Check, Share2, FileDown } from 'lucide-react';
import { escapeHtml } from '@/lib/security';

interface ExportMaterial {
  product_name: string;
  quantity: number;
  category: string;
  price: number | null;
  purchased?: boolean;
}

interface MaterialsExportProps {
  projectName: string;
  materials: ExportMaterial[];
  onClose: () => void;
}

export default function MaterialsExport({ projectName, materials, onClose }: MaterialsExportProps) {
  const [copied, setCopied] = useState(false);

  const total = materials.reduce((sum, item) => sum + (item.price || 0) * item.quantity, 0);
  const purchasedCount = materials.filter(m => m.purchased).length;

  // Group materials by category
  const groupedMaterials = materials.reduce((acc, item) => {
    const cat = item.category || 'general';
    if (!acc[cat]) acc[cat] = [];
    acc[cat].push(item);
    return acc;
  }, {} as Record<string, ExportMaterial[]>);

  // Generate plain text shopping list
  const generateTextList = (): string => {
    let text = `SHOPPING LIST: ${projectName}\n`;
    text += `${'='.repeat(50)}\n`;
    text += `Generated: ${new Date().toLocaleDateString()}\n`;
    text += `Items: ${materials.length} | Purchased: ${purchasedCount}\n`;
    text += `${'='.repeat(50)}\n\n`;

    for (const [category, items] of Object.entries(groupedMaterials)) {
      text += `${category.toUpperCase()}\n`;
      text += `${'-'.repeat(30)}\n`;
      items.forEach(item => {
        const checkbox = item.purchased ? '[x]' : '[ ]';
        const price = item.price ? `$${item.price.toFixed(2)}` : 'TBD';
        const itemTotal = item.price && item.quantity > 1
          ? ` (${item.quantity} x $${item.price.toFixed(2)} = $${(item.price * item.quantity).toFixed(2)})`
          : '';
        text += `${checkbox} ${item.product_name} (Qty: ${item.quantity}) - ${price}${itemTotal}\n`;
      });
      text += '\n';
    }

    text += `${'='.repeat(50)}\n`;
    text += `ESTIMATED TOTAL: $${total.toFixed(2)}\n`;
    text += `\nGenerated by DIY Helper`;

    return text;
  };

  // Generate CSV content
  const generateCSV = (): string => {
    const headers = ['Item', 'Quantity', 'Category', 'Unit Price', 'Total Price', 'Purchased'];
    const rows = materials.map(item => [
      `"${item.product_name.replace(/"/g, '""')}"`,
      item.quantity,
      item.category,
      item.price || '',
      item.price ? (item.price * item.quantity).toFixed(2) : '',
      item.purchased ? 'Yes' : 'No'
    ]);

    return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  };

  // Copy to clipboard
  const copyToClipboard = async () => {
    const text = generateTextList();
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  // Download as text file
  const downloadText = () => {
    const text = generateTextList();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName.replace(/[^a-z0-9]/gi, '-')}-shopping-list.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Download as CSV
  const downloadCSV = () => {
    const csv = generateCSV();
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName.replace(/[^a-z0-9]/gi, '-')}-materials.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Print list
  const printList = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to print the shopping list');
      return;
    }

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Shopping List - ${escapeHtml(projectName)}</title>
          <style>
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              padding: 40px;
              max-width: 800px;
              margin: 0 auto;
            }
            h1 {
              text-align: center;
              font-size: 24px;
              margin-bottom: 8px;
              color: #1a1a1a;
            }
            .subtitle {
              text-align: center;
              color: #666;
              font-size: 14px;
              margin-bottom: 24px;
            }
            .meta {
              display: flex;
              justify-content: space-between;
              padding: 12px 16px;
              background: #f5f5f5;
              border-radius: 8px;
              margin-bottom: 24px;
              font-size: 14px;
            }
            .category {
              margin-bottom: 20px;
            }
            .category-header {
              font-size: 14px;
              font-weight: 600;
              text-transform: uppercase;
              letter-spacing: 0.5px;
              color: #666;
              padding-bottom: 8px;
              border-bottom: 2px solid #e0e0e0;
              margin-bottom: 12px;
            }
            .item {
              display: flex;
              align-items: center;
              padding: 10px 0;
              border-bottom: 1px solid #eee;
            }
            .item:last-child { border-bottom: none; }
            .checkbox {
              width: 20px;
              height: 20px;
              border: 2px solid #ccc;
              border-radius: 4px;
              margin-right: 12px;
              flex-shrink: 0;
            }
            .checkbox.checked {
              background: #4A7C59;
              border-color: #4A7C59;
            }
            .item-name {
              flex: 1;
              font-size: 15px;
            }
            .item-name.purchased {
              text-decoration: line-through;
              color: #999;
            }
            .item-qty {
              color: #666;
              font-size: 13px;
              margin-right: 16px;
            }
            .item-price {
              font-weight: 600;
              color: #4A7C59;
              min-width: 80px;
              text-align: right;
            }
            .total {
              margin-top: 24px;
              padding-top: 16px;
              border-top: 3px solid #1a1a1a;
              display: flex;
              justify-content: space-between;
              align-items: center;
              font-size: 18px;
            }
            .total-label { font-weight: 600; }
            .total-amount {
              font-weight: 700;
              font-size: 24px;
              color: #4A7C59;
            }
            .footer {
              text-align: center;
              margin-top: 32px;
              padding-top: 16px;
              border-top: 1px solid #eee;
              color: #999;
              font-size: 12px;
            }
            @media print {
              body { padding: 20px; }
              .no-print { display: none; }
            }
          </style>
        </head>
        <body>
          <h1>Shopping List</h1>
          <div class="subtitle">${escapeHtml(projectName)}</div>

          <div class="meta">
            <span>Date: ${new Date().toLocaleDateString()}</span>
            <span>Items: ${materials.length}</span>
            <span>Purchased: ${purchasedCount}</span>
          </div>

          ${Object.entries(groupedMaterials).map(([cat, items]) => `
            <div class="category">
              <div class="category-header">${escapeHtml(cat)}</div>
              ${items.map(item => `
                <div class="item">
                  <div class="checkbox ${item.purchased ? 'checked' : ''}"></div>
                  <span class="item-name ${item.purchased ? 'purchased' : ''}">${escapeHtml(item.product_name)}</span>
                  <span class="item-qty">Qty: ${item.quantity}</span>
                  <span class="item-price">${item.price ? '$' + (item.price * item.quantity).toFixed(2) : 'TBD'}</span>
                </div>
              `).join('')}
            </div>
          `).join('')}

          <div class="total">
            <span class="total-label">ESTIMATED TOTAL</span>
            <span class="total-amount">$${total.toFixed(2)}</span>
          </div>

          <div class="footer">
            Generated by DIY Helper
          </div>

          <script>
            window.onload = function() { window.print(); }
          </script>
        </body>
      </html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
  };

  // Save as PDF (opens print dialog with PDF suggestion)
  const saveAsPDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to save as PDF');
      return;
    }

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Shopping List - ${escapeHtml(projectName)}</title>
          <style>
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              padding: 40px;
              max-width: 800px;
              margin: 0 auto;
            }
            h1 { text-align: center; font-size: 24px; margin-bottom: 8px; color: #1a1a1a; }
            .subtitle { text-align: center; color: #666; font-size: 14px; margin-bottom: 24px; }
            .meta {
              display: flex; justify-content: space-between;
              padding: 12px 16px; background: #f5f5f5; border-radius: 8px;
              margin-bottom: 24px; font-size: 14px;
            }
            .category { margin-bottom: 20px; }
            .category-header {
              font-size: 14px; font-weight: 600; text-transform: uppercase;
              letter-spacing: 0.5px; color: #666;
              padding-bottom: 8px; border-bottom: 2px solid #e0e0e0; margin-bottom: 12px;
            }
            .item {
              display: flex; align-items: center;
              padding: 10px 0; border-bottom: 1px solid #eee;
            }
            .item:last-child { border-bottom: none; }
            .checkbox {
              width: 20px; height: 20px; border: 2px solid #ccc;
              border-radius: 4px; margin-right: 12px; flex-shrink: 0;
            }
            .checkbox.checked { background: #4A7C59; border-color: #4A7C59; }
            .item-name { flex: 1; font-size: 15px; }
            .item-name.purchased { text-decoration: line-through; color: #999; }
            .item-qty { color: #666; font-size: 13px; margin-right: 16px; }
            .item-price { font-weight: 600; color: #4A7C59; min-width: 80px; text-align: right; }
            .total {
              margin-top: 24px; padding-top: 16px; border-top: 3px solid #1a1a1a;
              display: flex; justify-content: space-between; align-items: center; font-size: 18px;
            }
            .total-label { font-weight: 600; }
            .total-amount { font-weight: 700; font-size: 24px; color: #4A7C59; }
            .footer {
              text-align: center; margin-top: 32px; padding-top: 16px;
              border-top: 1px solid #eee; color: #999; font-size: 12px;
            }
            .pdf-hint {
              text-align: center; padding: 16px; background: #fffbeb;
              border: 1px solid #fcd34d; border-radius: 8px; margin-bottom: 24px;
              font-size: 14px; color: #92400e;
            }
            @media print { .pdf-hint { display: none; } body { padding: 20px; } }
          </style>
        </head>
        <body>
          <div class="pdf-hint">
            Select "Save as PDF" as the destination in the print dialog below.
          </div>
          <h1>Shopping List</h1>
          <div class="subtitle">${escapeHtml(projectName)}</div>
          <div class="meta">
            <span>Date: ${new Date().toLocaleDateString()}</span>
            <span>Items: ${materials.length}</span>
            <span>Purchased: ${purchasedCount}</span>
          </div>
          ${Object.entries(groupedMaterials).map(([cat, items]) => `
            <div class="category">
              <div class="category-header">${escapeHtml(cat)}</div>
              ${items.map(item => `
                <div class="item">
                  <div class="checkbox ${item.purchased ? 'checked' : ''}"></div>
                  <span class="item-name ${item.purchased ? 'purchased' : ''}">${escapeHtml(item.product_name)}</span>
                  <span class="item-qty">Qty: ${item.quantity}</span>
                  <span class="item-price">${item.price ? '$' + (item.price * item.quantity).toFixed(2) : 'TBD'}</span>
                </div>
              `).join('')}
            </div>
          `).join('')}
          <div class="total">
            <span class="total-label">ESTIMATED TOTAL</span>
            <span class="total-amount">$${total.toFixed(2)}</span>
          </div>
          <div class="footer">Generated by DIY Helper</div>
          <script>window.onload = function() { window.print(); }</script>
        </body>
      </html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
  };

  // Generate shareable link with encoded data
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [shareCopied, setShareCopied] = useState(false);

  const generateShareLink = () => {
    const shareData = {
      n: projectName,
      m: materials.map(m => ({
        p: m.product_name,
        q: m.quantity,
        c: m.category,
        $: m.price,
      })),
    };
    const encoded = btoa(encodeURIComponent(JSON.stringify(shareData)));
    const url = `${window.location.origin}/share#${encoded}`;
    setShareUrl(url);
  };

  const copyShareLink = async () => {
    if (!shareUrl) return;
    try {
      await navigator.clipboard.writeText(shareUrl);
      setShareCopied(true);
      setTimeout(() => setShareCopied(false), 2000);
    } catch {
      // Fallback
      const textarea = document.createElement('textarea');
      textarea.value = shareUrl;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setShareCopied(true);
      setTimeout(() => setShareCopied(false), 2000);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl p-6 max-w-md w-full shadow-2xl max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-xl font-bold text-[#3E2723]">Export Shopping List</h3>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-lg transition"
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        <div className="mb-4 p-3 bg-[#F5F0E6] rounded-xl">
          <p className="font-medium text-[#3E2723]">{projectName}</p>
          <p className="text-sm text-[#7D6B5D]">
            {materials.length} items • ${total.toFixed(2)} estimated
          </p>
        </div>

        <div className="grid grid-cols-3 gap-3 mb-6">
          <button
            onClick={printList}
            className="flex flex-col items-center gap-2 p-4 border-2 border-gray-200 rounded-xl
                       hover:border-[#5D7B93] hover:bg-[#E8F0F5] transition-all group"
          >
            <Printer className="w-8 h-8 text-gray-500 group-hover:text-[#5D7B93]" />
            <span className="font-medium text-[#3E2723]">Print</span>
            <span className="text-xs text-gray-500">Print-friendly view</span>
          </button>

          <button
            onClick={copyToClipboard}
            className="flex flex-col items-center gap-2 p-4 border-2 border-gray-200 rounded-xl
                       hover:border-[#4A7C59] hover:bg-[#E8F3EC] transition-all group"
          >
            {copied ? (
              <Check className="w-8 h-8 text-[#4A7C59]" />
            ) : (
              <Copy className="w-8 h-8 text-gray-500 group-hover:text-[#4A7C59]" />
            )}
            <span className="font-medium text-[#3E2723]">{copied ? 'Copied!' : 'Copy'}</span>
            <span className="text-xs text-gray-500">To clipboard</span>
          </button>

          <button
            onClick={downloadText}
            className="flex flex-col items-center gap-2 p-4 border-2 border-gray-200 rounded-xl
                       hover:border-[#C67B5C] hover:bg-[#FDF3ED] transition-all group"
          >
            <FileText className="w-8 h-8 text-gray-500 group-hover:text-[#C67B5C]" />
            <span className="font-medium text-[#3E2723]">Text</span>
            <span className="text-xs text-gray-500">Download .txt</span>
          </button>

          <button
            onClick={downloadCSV}
            className="flex flex-col items-center gap-2 p-4 border-2 border-gray-200 rounded-xl
                       hover:border-green-500 hover:bg-green-50 transition-all group"
          >
            <Download className="w-8 h-8 text-gray-500 group-hover:text-green-600" />
            <span className="font-medium text-[#3E2723]">CSV</span>
            <span className="text-xs text-gray-500">Excel/Sheets</span>
          </button>

          <button
            onClick={saveAsPDF}
            className="flex flex-col items-center gap-2 p-4 border-2 border-gray-200 rounded-xl
                       hover:border-[#9B7BA6] hover:bg-[#F3EDF5] transition-all group"
          >
            <FileDown className="w-8 h-8 text-gray-500 group-hover:text-[#9B7BA6]" />
            <span className="font-medium text-[#3E2723]">PDF</span>
            <span className="text-xs text-gray-500">Save as PDF</span>
          </button>

          <button
            onClick={generateShareLink}
            className="flex flex-col items-center gap-2 p-4 border-2 border-gray-200 rounded-xl
                       hover:border-[#5D7B93] hover:bg-[#E8F0F5] transition-all group"
          >
            <Share2 className="w-8 h-8 text-gray-500 group-hover:text-[#5D7B93]" />
            <span className="font-medium text-[#3E2723]">Share</span>
            <span className="text-xs text-gray-500">Create link</span>
          </button>
        </div>

        {/* Share link display */}
        {shareUrl && (
          <div className="mb-4 p-3 bg-[#E8F0F5] rounded-xl">
            <p className="text-xs text-[#5D7B93] font-medium mb-2">Shareable link:</p>
            <div className="flex gap-2">
              <input
                type="text"
                value={shareUrl}
                readOnly
                className="flex-1 px-3 py-1.5 text-xs bg-white border border-[#D4C8B8] rounded-lg text-[#3E2723] truncate"
              />
              <button
                onClick={copyShareLink}
                className="px-3 py-1.5 bg-[#5D7B93] text-white text-xs rounded-lg hover:bg-[#4A6274] transition flex items-center gap-1"
              >
                {shareCopied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                {shareCopied ? 'Copied' : 'Copy'}
              </button>
            </div>
          </div>
        )}

        <button
          onClick={onClose}
          className="w-full py-3 border-2 border-gray-200 rounded-xl font-medium
                     hover:bg-gray-50 transition text-[#5C4D42]"
        >
          Close
        </button>
      </div>
    </div>
  );
}
