'use client';

import { useEffect, useMemo } from 'react';
import { ArrowLeft, Printer, Check } from 'lucide-react';
import { useShoppingTrips } from '@/hooks/useShoppingTrips';
import { escapeHtml } from '@/lib/security';

interface ShoppingTripChecklistProps {
  tripId: string;
  onBack: () => void;
}

export default function ShoppingTripChecklist({ tripId, onBack }: ShoppingTripChecklistProps) {
  const { activeTrip, loading, fetchTripDetail, toggleItem } = useShoppingTrips(undefined);

  useEffect(() => {
    fetchTripDetail(tripId);
  }, [tripId, fetchTripDetail]);

  const grouped = useMemo(() => {
    if (!activeTrip?.items) return {};
    return activeTrip.items.reduce((acc, item) => {
      const cat = item.category || 'General';
      if (!acc[cat]) acc[cat] = [];
      acc[cat].push(item);
      return acc;
    }, {} as Record<string, typeof activeTrip.items>);
  }, [activeTrip?.items]);

  const totalItems = activeTrip?.items.length || 0;
  const purchasedCount = activeTrip?.items.filter(i => i.purchased).length || 0;
  const remainingTotal = activeTrip?.items
    .filter(i => !i.purchased)
    .reduce((sum, i) => sum + ((i.estimated_price || 0) * i.quantity), 0) || 0;
  const spentTotal = activeTrip?.items
    .filter(i => i.purchased)
    .reduce((sum, i) => sum + ((i.estimated_price || 0) * i.quantity), 0) || 0;

  const handleToggle = async (itemId: string, currentState: boolean) => {
    await toggleItem(tripId, itemId, !currentState);
  };

  const handlePrint = () => {
    if (!activeTrip) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const categorySections = Object.entries(grouped).map(([category, items]) => {
      const categoryTotal = items.reduce((sum, i) => sum + ((i.estimated_price || 0) * i.quantity), 0);
      const itemRows = items.map(item => `
        <div class="item">
          <div class="checkbox ${item.purchased ? 'checked' : ''}"></div>
          <div class="item-name">${escapeHtml(item.product_name)}</div>
          <div class="item-qty">x${item.quantity}</div>
          <div class="item-price">${item.estimated_price ? '$' + (item.estimated_price * item.quantity).toFixed(2) : '\u2014'}</div>
        </div>
      `).join('');
      return `
        <div class="category">
          <div class="category-header">${escapeHtml(category)} <span style="float:right">$${categoryTotal.toFixed(2)}</span></div>
          ${itemRows}
        </div>
      `;
    }).join('');

    printWindow.document.write(`<!DOCTYPE html><html><head>
      <title>Shopping Trip - ${escapeHtml(activeTrip.trip.name)}</title>
      <style>
        *{box-sizing:border-box;margin:0;padding:0}
        body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;padding:32px;max-width:700px;margin:0 auto}
        h1{font-size:20px;margin-bottom:4px}
        .meta{color:#666;font-size:12px;margin-bottom:20px}
        .category{margin-bottom:16px}
        .category-header{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;color:#666;padding-bottom:6px;border-bottom:2px solid #ddd;margin-bottom:8px}
        .item{display:flex;align-items:center;padding:6px 0;border-bottom:1px solid #eee;gap:10px}
        .checkbox{width:16px;height:16px;border:2px solid #ccc;border-radius:3px;flex-shrink:0}
        .checkbox.checked{background:#4A7C59;border-color:#4A7C59}
        .item-name{flex:1;font-size:13px}
        .item-qty{font-size:12px;color:#888;width:30px;text-align:center}
        .item-price{font-size:13px;font-weight:500;width:60px;text-align:right}
        .total{margin-top:16px;padding-top:12px;border-top:2px solid #333;display:flex;justify-content:space-between;font-weight:700;font-size:16px}
        .footer{margin-top:20px;text-align:center;color:#aaa;font-size:10px}
      </style>
    </head><body>
      <h1>${escapeHtml(activeTrip.trip.name)}</h1>
      <div class="meta">${new Date(activeTrip.trip.created_at).toLocaleDateString()} \u00b7 ${totalItems} items \u00b7 ${purchasedCount} purchased</div>
      ${categorySections}
      <div class="total"><span>Total</span><span>$${(remainingTotal + spentTotal).toFixed(2)}</span></div>
      <div class="footer">Generated by DIY Helper</div>
    </body></html>`);
    printWindow.document.close();
    printWindow.print();
  };

  if (loading && !activeTrip) {
    return <div className="text-sm text-earth-brown-light py-8 text-center">Loading checklist...</div>;
  }

  if (!activeTrip) {
    return <div className="text-sm text-rust py-8 text-center">Trip not found</div>;
  }

  return (
    <div className="space-y-3">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <button onClick={onBack} className="p-1 rounded hover:bg-earth-tan/30 transition-colors">
            <ArrowLeft className="w-4 h-4 text-earth-brown" />
          </button>
          <div>
            <h3 className="text-sm font-semibold text-foreground">{activeTrip.trip.name}</h3>
            <p className="text-xs text-earth-brown-light">
              {purchasedCount} of {totalItems} purchased · Est. ${remainingTotal.toFixed(0)} remaining
            </p>
          </div>
        </div>
        <div className="flex gap-1">
          <button onClick={handlePrint} className="p-1.5 rounded hover:bg-earth-tan/30 transition-colors" title="Print">
            <Printer className="w-4 h-4 text-earth-brown-light" />
          </button>
        </div>
      </div>

      {/* Items grouped by category */}
      {Object.entries(grouped).map(([category, items]) => (
        <div key={category}>
          <div className="text-[10px] font-semibold uppercase tracking-wider text-earth-brown-light pb-1.5 mb-2 border-b border-earth-sand/30">
            {category}
          </div>
          {items.map(item => (
            <button
              key={item.id}
              onClick={() => handleToggle(item.id, item.purchased)}
              className="flex items-center gap-3 w-full text-left py-2.5 border-b border-earth-tan/20 transition-colors hover:bg-earth-tan/10 -mx-1 px-1 rounded"
            >
              <div className={`w-5 h-5 rounded-md flex-shrink-0 flex items-center justify-center transition-colors ${
                item.purchased
                  ? 'bg-forest-green'
                  : 'border-2 border-earth-sand'
              }`}>
                {item.purchased && <Check className="w-3 h-3 text-white" />}
              </div>
              <div className={`flex-1 min-w-0 ${item.purchased ? 'line-through opacity-40' : ''}`}>
                <div className="text-sm text-foreground truncate">{item.product_name}</div>
                {item.quantity > 1 && (
                  <div className="text-xs text-earth-brown-light">Qty: {item.quantity}</div>
                )}
              </div>
              <div className={`text-sm flex-shrink-0 ${item.purchased ? 'text-earth-brown-light/40' : 'text-earth-brown'}`}>
                {item.estimated_price ? `$${(item.estimated_price * item.quantity).toFixed(0)}` : '\u2014'}
              </div>
            </button>
          ))}
        </div>
      ))}

      {/* Bottom summary */}
      <div className="flex justify-between items-center pt-3 border-t border-earth-sand/40">
        <div>
          <div className="text-xs text-earth-brown-light">Remaining</div>
          <div className="text-lg font-bold text-forest-green">${remainingTotal.toFixed(2)}</div>
        </div>
        <div className="text-right">
          <div className="text-xs text-earth-brown-light">Spent</div>
          <div className="text-lg font-bold text-earth-brown-light">${spentTotal.toFixed(2)}</div>
        </div>
      </div>
    </div>
  );
}
